### ISSUE TITLE
add cancel buttons to withdraw, deposit, and transfer screens

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/Personal-Banking-Pro#15]
These screens should have cancel buttons to the left of the Confirm buttons:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/53918934/164945670-c6f569e2-185c-43ba-8282-37bef9c43365.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/53918934/164945673-36bff2a0-e2a8-4b86-bc72-250d5d9ada73.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/53918934/164945679-6f65d940-67d6-474d-bc04-d599acf51855.png">

**Comment by Jasman04** [comment]
Added back button to each of those screens
