### ISSUE TITLE
Withdrawing and Transferring Percent Boxes

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/Personal-Banking-Pro#20]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/53918934/167918484-47fcd77a-21a9-47b6-a30a-37fc26a255c0.png">

The Amount box should be to preview the selected amount, as in if the "Custom" Checkbox is ticked, we'll have that value displayed next to "Amount", but if one of the % boxes are ticked, such as 20%, the amount preview should be calculated and put next to its text field

**Comment by Daggerpov** [comment]
Calculations done, need to test Custom value inputting.  @Jasman04 let me know if you can click on the "Custom" checkbox, enter a value next to it in the text input, then its amount should appear just like for the percentages. Additionally, please edit the font size. 
<img width="342" alt="image" src="https://user-images.githubusercontent.com/53918934/167939077-1b142b4f-fa83-436c-a948-33ce1776e79c.png">

**Comment by Jasman04** [comment]
looks good and thanks for making this feature
